### ISSUE TITLE
Kubernetes Dashboard Installation Error

### ISSUE THREAD

**Issue by tcbuzor** [mojaloop/docs#106]
The document : Mojaloop_Phase2_Wrap-up_Deployment-Day3 has an outdated URL for Kubernetes dashboard as well as the old login screen with "skip button"

While following the steps in the document , I run into a "Not Found" error while install the dashboard. The new URL for dashboard is https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml

The following steps will install the dashboard and allow the user login as admin user with an authorization token:

**1. Deploy Dashoboard**
	$ kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml

**2. Enable Dashboard access from local workstation**
   $ kubectl proxy
   
**3. Access Dashboard at:**
    
   http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/
   
**4. Generate Authentication Token**  
  
  _4.1: create yaml file named dashboard-adminuser.yaml with following content:_
  
               apiVersion: rbac.authorization.k8s.io/v1
		kind: ClusterRoleBinding
		metadata:
		  name: admin-user
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: cluster-admin
               subjects:
                - kind: ServiceAccount
                name: admin-user
                namespace: kube-system
		  
  _4.2: Find token with following command:_
  
      $ kubectl -n kube-system describe secret $(kubectl -n kube-system get secret | grep admin-user | awk '{print $1}')
	  
	  Sample output:
	  
		Name:         admin-user-token-6gl6l
		Namespace:    kube-system
		Labels:       <none>
		Annotations:  kubernetes.io/service-account.name=admin-user
					  kubernetes.io/service-account.uid=b16afba9-dfec-11e7-bbb9-901b0e532516

		Type:  kubernetes.io/service-account-token

		Data
		====
		ca.crt:     1025 bytes
		namespace:  11 bytes
		token:      eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlc
		            y5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2Vj
					cmV0Lm5hbWUiOiJhZG1pbi11c2VyLXRva2VuLTZnbDZsIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291
					bnQubmFtZSI6ImFkbWluLXVzZXIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJiMTZh
					ZmJhOS1kZmVjLTExZTctYmJiOS05MDFiMGU1MzI1MTYiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06YWRta
					W4tdXNlciJ9.M70CU3lbu3PP4OjhFms8PVL5pQKj-jj4RNSLA4YmQfTXpPUuxqXjiTf094_Rzr0fgN_IVX6gC4fiNUL5ynx9KU-lkPfk
					0HnX8scxfJNzypL039mpGt0bbe1IXKSIRaq_9VW59Xz-yBUhycYcKPO9RM2Qa1Ax29nqNVko4vLn1_1wPqJ6XSq3GYI8anTzV8Fku4
					jasUwjrws6Cn6_sPEGmL54sq5R4Z5afUtv-mItTmqZZdxnkRqcJLlg2Y8WbCPogErbsaCDJoABQ7ppaqHetwfM_0yMun6ABOQbIwwl8
					pspJhpplKwyo700OSpvTT9zlBsu-b35lzXGBRHzv5g_RA
					
  _4.3	 Copy the token and paste into "Enter token field" on login screen. Click Sign in button and you_ should be logged in as an admin.

**Comment by elnyry** [comment]
Thanks Tonio for the these steps, I'm sure these will be very helpful.

However, this is expected since the presentation "Mojaloop_Phase2_Wrap-up_Deployment-Day3" you referenced was used in September and its natural that URLs change, versions get upgraded, etc.

**Comment by tcbuzor** [comment]
I do understand URLs and versions change so I raised the issue as well as the working steps so that the official document can be updated. I am also willing to help with the update.

**Comment by elnyry** [comment]
Yes, appreciate it, thanks Tonio.

**Comment by elnyry** [comment]
Closing this now. Please open an issue on mojaloop/project in future for any related items
