### ISSUE TITLE
Update tools and technologies Doc

### ISSUE THREAD

**Issue by kjw000** [mojaloop/docs#114]
As a Mojaloop contributor I need a clear understanding of what tools and technologies are leveraged Mojaloop.

- update/review https://github.com/mojaloop/mojaloop/blob/master/contribute/Tools-technology-and-process-choices.md

Acceptance Criteria:
- all new links work
- users can install any software
- users know what tools to use

**Comment by elnyry** [comment]
This seems to be updated now.

@kjw000 please re-open if thats not the case
