### ISSUE TITLE
central_ledger schema in docs/CentralServices/data_diagrams/central-ledger-ddl-MySQLWorkbench.sql does not reflect actual schema created on deployment

### ISSUE THREAD

**Issue by bushjames** [mojaloop/docs#43]
The schema described in the DDL here: docs/CentralServices/data_diagrams/central-ledger-ddl-MySQLWorkbench.sql does not contain the "charge" table. However, after deploying mojaloop we notice a charge table in the schema. Please can you confirm if the charge table should be deployed by the code (assumed to be a knex migration?) or if it is missing from the documented DDL.

**Comment by rmothilal** [comment]
Hi James,

This was done on the rewrite on the database so you would need the latest codebase also.
The latest migration do not create a charge table. Which branch of central-ledger are you using?

Kind regards,
Rajiv

**Comment by bushjames** [comment]
Hi Rajiv,

**Comment by rmothilal** [comment]
Hey James, 

The DDL is for the develop-pi3 branch code. 

Kind regards,
Rajiv

**Comment by bushjames** [comment]
Many thanks Rajiv. Understood.

**Comment by elnyry** [comment]
Thanks Rajiv, closing this..
