### ISSUE TITLE
seq-prepare-1.1.1.a update required for spelling and publishing event detail

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/docs#69]
**Summary**:
Ref: https://github.com/mojaloop/docs/blob/develop/CentralServices/seq_diagrams/seq-prepare-1.1.1.a.svg

The following section: `16. Publish Notification event for Payer with the completed transer`

Requires two updates:
1. Spelling error. `transer` should be `transfers`
2. The design needs to be more descriptive of how the message is being published. A new event action has been created to handle the duplicate Prepare POST requests `prepare-duplicate`, and as such, the design should show this detail. This is a result of a fix for the following issue: https://github.com/mojaloop/project/issues/424 done by @shashi165 

**Severity**:
Medium

**Priority**:
Low

**Expected Behavior**
Ref: https://github.com/mojaloop/docs/blob/develop/CentralServices/seq_diagrams/seq-prepare-1.1.1.a.svg

The following section: `16. Publish Notification event for Payer with the completed transer`

1. Spelling error. `transer` should be `transfers`
2. The design needs to be more descriptive of how the message is being published. A new event action has been created to handle the duplicate Prepare POST requests `prepare-duplicate`, and as such the design should show this detail.

**Steps to Reproduce**
  1. Ref: https://github.com/mojaloop/docs/blob/develop/CentralServices/seq_diagrams/seq-prepare-1.1.1.a.svg

**Specifications**
  - Component: seq-prepare-1.1.1.a.plantuml
  - Version: v1.1.1a
  - Platform: PlantUML
  - Subsystem: n/a
  - Type of testing: Manaul
  - Bug found/raised by: @mdebarros

**Notes**:
- Contact @shashi165 for detail on what changes were made to accommodate the `prepare-duplicate`

**Comment by elnyry** [comment]
PR - https://github.com/mojaloop/docs/pull/71

**Comment by elnyry** [comment]
Resolved by this one - https://github.com/mojaloop/project/issues/429
