### ISSUE TITLE
DFSP Admin

### ISSUE THREAD

**Issue by wshbair** [mojaloop/docs#93]
What is the default admin username/password for dfsp-admin, EC2 deployment ??

**Comment by kjw000** [comment]
Hi wshbair - our services are meant to be deployed on your own instance.  Perhaps we can chat and I can provide you with a bit more details on Mojaloop and how we can assist you.   Please feel free to contact me at kimw@crosslaketech.com or on gitter at - https://gitter.im/mojaloop/mojaloop
